spring:
  application:
    name: FitMeet

  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:templates/
    check-template-location: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fitmeet?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: seodong
    password: Tjgud990517!

  web:
    resources:
      static-locations: /static/

mybatis:
  type-aliases-package: com.ssafy.fitmeet.domain.*.entity
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'NULL'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 9090

jwt:
  secret: "fitmeettsttestesttest1235test546testesttest"
  access-token-validity-in-ms: 3600000
  refresh-token-validity-in-ms: 1209600000
  
app:
  cookie:
    access-max-age: 1800
    refresh-max-age: 1209600
  
open-api:
  nutri : 
    end-point : "https://apis.data.go.kr/1471000/FoodNtrCpntDbInfo02/getFoodNtrCpntDbInq02"
    key : "r5iww18IGLqktX1nmaQWV6s90R0aenR%2Fwf9cFRgFPyvlonWWZftRaz8MZDUrlhzluQ89dgNpaVwQN%2F%2BNRVvGqA%3D%3D"

logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.ssafy.fitmeet: DEBUG
    
---
spring:
  config:
    activate:
      on-profile: dev

app:
  cookie:
    same-site: Lax
    secure: false
    
---
spring:
  config:
    activate:
      on-profile: prod

app:
  cookie:
    same-site: None
    secure: true

